### ISSUE TITLE
Seek your suggestion on the speed of onnx model

### ISSUE THREAD

**Issue by vincent341** [fateshelled/unimatch_onnx#5]
Hello! Thank you very much for sharing the fantastic ONNX model for Unimatch. I attempted to create the ONNX version of Unimatch on my own, but I have noticed that it runs four times slower than yours and even slower than the Pytroch version. Would you be willing to provide some suggestions on how to address it? It would be greatly appreciated if you could share your scripts for generating the ONNX models.

**Comment by fateshelled** [comment]
Hello.
I have lost my conversion script.
Could you share your scripts and ONNX models with me?

**Comment by vincent341** [comment]
The [onnx model](https://drive.google.com/file/d/1veMpX8jRJlOVrGQR1YmQUexgiSW7POBK/view?usp=drive_link) and its [profile document](https://drive.google.com/file/d/1ITXmOP0-FRxACx74hLo6qq6y1F2gr4YP/view?usp=drive_link) are available. By visualizing the profile document using chrome, I found that the operation taking the longest time is **GridSample**, and its provider is "CPUExecutionProvide". I believe if its provider is "CUDAExecutionProvider", the time would be reduced. Do you have any idea how to correct it to "CUDAExecutionProvider"?

**Comment by fateshelled** [comment]
Thanks for sharing the model.
Please let me know your OS and Python version, as well as the version of the libraries you used for conversion and inference.
If possible, please also share the script you used for the conversion.

**Comment by fateshelled** [comment]
Thanks for your email.

I tried to convert to onnx model with the script you gave me, but I couldn't convert it properly.
Which Pytorch weight did you use and what argument did you use to do the conversion?

**Comment by fateshelled** [comment]
I have confirmed that your model is slow to infer.

I don't know the cause, but the main difference between your code and mine is the way you modified the Unimatch model class.

Your code defined variables in the function to make the "forward" function argument only an image, whereas I specified them in the constructor argument.
I also removed unnecessary if statements, etc. to make the class dedicated to the stereo model (not sure of the effect on the conversion and inference speed).

Are the model parameters such as attn_type correct?

**Comment by vincent341** [comment]
> I have confirmed that your model is slow to infer.
> 
> I don't know the cause, but the main difference between your code and mine is the way you modified the Unimatch model class.
> 
> Your code defined variables in the function to make the "forward" function argument only an image, whereas I specified them in the constructor argument. I also removed unnecessary if statements, etc. to make the class dedicated to the stereo model (not sure of the effect on the conversion and inference speed).
> 
> Are the model parameters such as attn_type correct?

I'm truly grateful for your assistance. Regarding attn_type, I've opted for 'self_swin2d_cross_swin1d'. I also noticed that your ONNX file is approximately 120MB, whereas mine is around 30MB. Do you think this size difference could provide any insights?
